apiVersion: v1
kind: Service
metadata:
  name: {{ include "zoo3-lab.fullname" . }}
  labels:
    {{- include "zoo3-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: port1
      protocol: TCP
      name: port1
    - port: {{ .Values.service.port2 }}
      targetPort: port2
      protocol: TCP
      name: port2
    - port: {{ .Values.service.port3 }}
      targetPort: port3
      protocol: TCP
      name: port3
  selector:
    {{- include "zoo3-lab.selectorLabels" . | nindent 4 }}
